In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [6]:
df1 = pd.read_csv(r'/Users/pratishtha/Downloads/GTD_Assignm/dataset/data-society-global-terrorism-data/gtd_70to91_49566.csv',encoding='latin1')
df2 = pd.read_csv(r'/Users/pratishtha/Downloads/GTD_Assignm/dataset/data-society-global-terrorism-data/gtd_92to11_no 93_55072.csv',encoding='latin1')
df3 = pd.read_csv(r'/Users/pratishtha/Downloads/GTD_Assignm/dataset/data-society-global-terrorism-data/gtd_12to15_52134.csv',encoding='latin1')
df4 = pd.read_csv(r'/Users/pratishtha/Downloads/GTD_Assignm/dataset/data-society-global-terrorism-data/gtd1993_748.csv',encoding='latin1')

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/3679133339.py:1: DtypeWarning: Columns (4,17,61,62,123) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(r'/Users/pratishtha/Downloads/GTD_Assignm/dataset/data-society-global-terrorism-data/gtd_70to91_49566.csv',encoding='latin1')
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/3679133339.py:2: DtypeWarning: Columns (4,61,62,66,116,117,123) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(r'/Users/pratishtha/Downloads/GTD_Assignm/dataset/data-society-global-terrorism-data/gtd_92to11_no 93_55072.csv',encoding='latin1')
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/3679133339.py:3: DtypeWarning: Columns (66,116,117) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv(r'/Users/pratishtha/Downloads/GTD_Assignm/dataset/data-society-global-terrorism-data/gtd_12to15_52134.csv',encoding='latin1')

In [7]:
df = pd.concat([df1, df2, df3, df4], ignore_index=True)

In [8]:
df.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,0,0,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0.0,0.0,0.0,0.0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0.0,1.0,1.0,1.0,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9.0,-9.0,1.0,1.0,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9.0,-9.0,1.0,1.0,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9.0,-9.0,1.0,1.0,NaN

In [ ]:
imp_cols = df[['eventid','iyear','imonth','iday','extended','country','country_txt','region','region_txt','provstate','city','latitude','longitude','specificity','vicinity','crit1','crit2','crit3','doubtterr','multiple','success','suicide','attacktype1','attacktype1_ˀtxt','targtype1','targtype1_txt','targsubtype1','targsubtype1_txt','target1','natlty1','natlty1_txt','gname','guncertain1','nperps','nperpcap','claimed','weaptype1','weaptype1_txt','weapsubtype1','weapsubtype1_txt','nkill','nkillus','nkillter','nwound','nwoundus','property','propextent','propextent_txt','propvalue','ishostkid','INT_LOG','INT_IDEO','INT_MISC','INT_ANY']]

In [10]:
imp_cols.shape

(157520, 54)

In [11]:
null_prcnt = imp_cols.isnull().sum()/imp_cols.shape[0] * 100

In [12]:
null_prcnt

eventid              0.000000
iyear                0.000000
imonth               0.000000
iday                 0.000000
extended             0.000000
country              0.000000
country_txt          0.000000
region               0.000000
region_txt           0.000000
provstate            9.217877
city                 0.283773
latitude             3.343702
longitude            3.343702
specificity          0.474860
vicinity             0.000000
crit1                0.000000
crit2                0.000000
crit3                0.000000
doubtterr            0.000635
multiple             0.000000
success              0.000635
suicide              0.000000
attacktype1          0.000000
attacktype1_txt      0.000000
targtype1            0.000000
targtype1_txt        0.000000
targsubtype1         5.651981
targsubtype1_txt     0.474860
target1              0.413916
natlty1              0.789106
natlty1_txt          0.000000
gname                0.000000
guncertain1          0.239970
nperps              45.503428
nperpcap            44.291519
claimed             41.988954
weaptype1            0.000000
weaptype1_txt        0.000000
weapsubtype1        11.412519
weapsubtype1_txt     0.000000
nkill                5.688801
nkillus             40.942737
nkillter            42.178136
nwound               9.041392
nwoundus            41.116684
property             0.053327
propextent          63.948705
propextent_txt       0.000000
propvalue           80.106653
ishostkid            0.113002
INT_LOG              0.474860
INT_IDEO             0.474860
INT_MISC             0.474860
INT_ANY              0.474860
dtype: float64

In [13]:
pd.set_option('display.max_columns',None)

In [14]:
imp_cols[imp_cols['city'].isna()]

,eventid,iyear,imonth,iday,extended,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,crit1,crit2,crit3,doubtterr,multiple,success,suicide,attacktype1,attacktype1_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,target1,natlty1,natlty1_txt,gname,guncertain1,nperps,nperpcap,claimed,weaptype1,weaptype1_txt,weapsubtype1,weapsubtype1_txt,nkill,nkillus,nkillter,nwound,nwoundus,property,propextent,propextent_txt,propvalue,ishostkid,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
79358,200601190011,2006,1,19,0,205,Thailand,5,Southeast Asia,Narathiwat,NaN,6.190088,101.797961,3.0,0,1,1,1,0.0,0,1.0,0,2,Armed Assault,14,Private Citizens & Property,NaN,.,Supasilp Woh,205.0,Thailand,Unknown,0.0,NaN,0.0,0.0,5,Firearms,5.0,Unknown Gun Type,1.0,0.0,0.0,0.0,0.0,0.0,NaN,.,NaN,0.0,-9.0,-9.0,0.0,-9.0
79359,200601190012,2006,1,19,0,205,Thailand,5,Southeast Asia,Pattani,NaN,6.700696,101.433915,3.0,0,1,1,1,0.0,0,1.0,0,2,Armed Assault,14,Private Citizens & Property,68.0,Named Civilian,Parn Priklek,205.0,Thailand,Unknown,0.0,NaN,0.0,0.0,5,Firearms,5.0,Unknown Gun Type,1.0,0.0,0.0,0.0,0.0,0.0,NaN,.,NaN,0.0,-9.0,-9.0,0.0,-9.0
79450,200601240022,2006,1,24,0,205,Thailand,5,Southeast Asia,Pattani,NaN,6.700696,101.433915,4.0,0,1,1,1,0.0,0,1.0,0,2,Armed Assault,2,Government (General),18.0,"Government Personnel (excluding police, military)",government employee Bahem Kalem,205.0,Thailand,Unknown,0.0,NaN,0.0,0.0,5,Firearms,2.0,Automatic Weapon,1.0,0.0,0.0,0.0,0.0,-9.0,NaN,.,NaN,0.0,-9.0,-9.0,0.0,-9.0
79483,200601270007,2006,1,27,0,205,Thailand,5,Southeast Asia,Yala,NaN,6.202025,101.252379,4.0,0,1,1,1,0.0,0,1.0,0,2,Armed Assault,14,Private Citizens & Property,68.0,Named Civilian,Apisith Gueaji,205.0,Thailand,Unknown,0.0,2.0,0.0,0.0,5,Firearms,5.0,Unknown Gun Type,1.0,0.0,0.0,0.0,0.0,-9.0,NaN,.,NaN,0.0,-9.0,-9.0,0.0,-9.0
79852,200602210011,2006,2,21,0,205,Thailand,5,Southeast Asia,Yala (Province),NaN,6.202025,101.252379,3.0,0,1,1,1,0.0,0,1.0,0,2,Armed Assault,3,Police,25.0,Police Security Forces/Officers,Sergeant Major Prapon Suwankota,205.0,Thailand,Unknown,0.0,NaN,0.0,0.0,5,Firearms,5.0,Unknown Gun Type,2.0,0.0,1.0,0.0,0.0,0.0,NaN,.,NaN,0.0,-9.0,-9.0,0.0,-9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103267,201110100014,2011,10,10,0,95,Iraq,10,Middle East & North Africa,Basra,NaN,30.293114,47.292389,4.0,0,1,1,1,0.0,0,0.0,0,3,Bombing/Explosion,21,Utilities,108.0,Oil,Oil pipelines were targeted in the attempted b...,95.0,Iraq,Unknown,0.0,-99.0,-99.0,0.0,6,Explosives/Bombs/Dynamite,17.0,Other Explosive Type,0.0,0.0,0.0,0.0,0.0,0.0,NaN,.,NaN,0.0,-9.0,-9.0,0.0,-9.0
103317,201110140008,2011,10,14,0,93,Indonesia,5,Southeast Asia,Papua,NaN,-2.534382,140.709304,4.0,0,1,1,1,0.0,0,1.0,0,2,Armed Assault,4,Military,34.0,"Military Personnel (soldiers, troops, officers...",The targets were military officers.,93.0,Indonesia,Unknown,0.0,-99.0,0.0,0.0,5,Firearms,5.0,Unknown Gun Type,3.0,0.0,0.0,3.0,0.0,-9.0,NaN,.,NaN,0.0,-9.0,-9.0,0.0,-9.0
103394,201110210005,2011,10,21,0,93,Indonesia,5,Southeast Asia,Papua,NaN,-2.534382,140.709304,4.0,0,1,1,1,0.0,0,1.0,0,2,Armed Assault,14,Private Citizens & Property,67.0,Unnamed Civilian/Unspecified,Civilians,93.0,Indonesia,Unknown,0.0,-99.0,0.0,0.0,5,Firearms,5.0,Unknown Gun Type,3.0,0.0,0.0,1.0,0.0,0.0,NaN,.,NaN,0.0,-9.0,-9.0,0.0,-9.0
103407,201110230002,2011,10,23,0,4,Afghanistan,6,South Asia,Parwan,NaN,34.963098,68.810885,4.0,1,1,1,1,0.0,0,0.0,1,1,Assassination,2,Government (General),18.0,"Government Personnel (excluding police, military)",The Afghan Interior Minister was targeted in t...,4.0,Afghanistan,Unknown,0.0,1.0,0.0,0.0,6,Explosives/Bombs/Dynamite,13.0,Suicide (carried bodily by human being),1.0,0.0,1.0,0.0,0.0,-9.0,NaN,.,NaN,0.0,-9.0,-9.0,0.0,-9.0
104248,201112030021,2011,12,3,0,93,Indonesia,5,Southeast Asia,Papua,NaN,-2.533000,140.717000,4.0,1,1,1,1,0.0,0,1.0,0,8,Unarmed Assault,3,Police,25.0,Police Security Forces/Officers,Police Officers,93.0,Indonesia,Free Papua Movement (OPM-Organisasi Papua Merd...,1.0,-99.0,0.0,0.0,12,Other,NaN,.,2.0,0.0,0.0,0.0,0.0,0.0,NaN,.,NaN,0.0,1.0,1.0,0.0,1.0

In [15]:
imp_cols['city'].fillna('unknown',inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/322416630.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  imp_cols['city'].fillna('unknown',inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/322416630.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imp_cols['city'].fillna('unknown',inplace=True)

In [16]:
imp_cols['specificity'].fillna(0,inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/4189109873.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  imp_cols['specificity'].fillna(0,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/4189109873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imp_cols['specificity'].fillna(0,inplace=True)

In [17]:
imp_cols['doubtterr'].fillna(-9,inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/918357602.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  imp_cols['doubtterr'].fillna(-9,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/918357602.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imp_cols['doubtterr'].fillna(-9,inplace=True)

In [18]:
imp_cols['success'].fillna(0,inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/4149791245.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  imp_cols['success'].fillna(0,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/4149791245.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imp_cols['success'].fillna(0,inplace=True)

In [19]:
def create_date_column(df):
    def create_date(row):
        if row['iyear'] == 0 or row['imonth'] == 0 or row['iday'] == 0:
            return np.nan
        else:
            return f"{int(row['iyear'])}/{int(row['imonth']):02d}/{int(row['iday']):02d}"

    df['date'] = df.apply(create_date, axis=1)
    
    return df

In [20]:
data = create_date_column(df=imp_cols)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/3469961530.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['date'] = df.apply(create_date, axis=1)

In [21]:
data['date'] = pd.to_datetime(data['date'], format='%Y/%m/%d', errors='coerce')

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/3565236449.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['date'] = pd.to_datetime(data['date'], format='%Y/%m/%d', errors='coerce')

In [22]:
data['targsubtype1'].fillna(0,inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/874887649.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['targsubtype1'].fillna(0,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/874887649.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['targsubtype1'].fillna(0,inplace=True)

In [23]:
data['targsubtype1_txt'].fillna('unknown',inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/3115109451.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['targsubtype1_txt'].fillna('unknown',inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/3115109451.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['targsubtype1_txt'].fillna('unknown',inplace=True)

In [24]:
data['target1'] = data['target1'].fillna(data['targtype1_txt'])

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/1841473476.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['target1'] = data['target1'].fillna(data['targtype1_txt'])

In [25]:
data['natlty1'].fillna(0,inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/3434669302.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['natlty1'].fillna(0,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/3434669302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['natlty1'].fillna(0,inplace=True)

In [26]:
data['natlty1_txt'] = data['natlty1_txt'].replace('.','unknown')

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/101113347.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['natlty1_txt'] = data['natlty1_txt'].replace('.','unknown')

In [27]:
data['targsubtype1_txt'] = data['targsubtype1_txt'].replace('.','unknown')

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/464990983.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['targsubtype1_txt'] = data['targsubtype1_txt'].replace('.','unknown')

In [28]:
data['guncertain1'].fillna(1,inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/3024390376.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['guncertain1'].fillna(1,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/3024390376.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['guncertain1'].fillna(1,inplace=True)

In [29]:
null_prcnt1=data.isnull().sum()/data.shape[0] * 100

In [30]:
data['weapsubtype1'].fillna(0,inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/1095099802.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['weapsubtype1'].fillna(0,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/1095099802.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['weapsubtype1'].fillna(0,inplace=True)

In [31]:
data['weapsubtype1_txt'] = data['weapsubtype1_txt'].replace('.','unknown')

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/271943341.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['weapsubtype1_txt'] = data['weapsubtype1_txt'].replace('.','unknown')

In [32]:
null_prcnt1[null_prcnt1 > 40]

nperps        45.503428
nperpcap      44.291519
claimed       41.988954
nkillus       40.942737
nkillter      42.178136
nwoundus      41.116684
propextent    63.948705
propvalue     80.106653
dtype: float64

In [33]:
drop_clms = null_prcnt[null_prcnt>50].keys()
data.drop(columns=drop_clms,inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/1116361083.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns=drop_clms,inplace=True)

In [34]:
data['INT_LOG'].fillna(-9,inplace=True)
data['INT_IDEO'].fillna(-9,inplace=True)
data['INT_MISC'].fillna(-9,inplace=True)
data['INT_ANY'].fillna(-9,inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/2420767950.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['INT_LOG'].fillna(-9,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/2420767950.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['INT_LOG'].fillna(-9,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/2420767950.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['INT_IDEO'].fillna(-9,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/2420767950.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['INT_IDEO'].fillna(-9,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/2420767950.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['INT_MISC'].fillna(-9,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/2420767950.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['INT_MISC'].fillna(-9,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/2420767950.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['INT_ANY'].fillna(-9,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/2420767950.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['INT_ANY'].fillna(-9,inplace=True)

In [35]:
data['ishostkid'].fillna(-9,inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/2162726347.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['ishostkid'].fillna(-9,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/2162726347.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ishostkid'].fillna(-9,inplace=True)

In [36]:
data['property'].unique()

array([ 0.,  1., -9., nan])

In [37]:
data['property'].fillna(-9,inplace=True)

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/1385031956.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['property'].fillna(-9,inplace=True)
/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/1385031956.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['property'].fillna(-9,inplace=True)

In [38]:
data['propextent_txt'] = data['propextent_txt'].replace('.','unknown')

/var/folders/ds/2jg6pvd14q15mfkt69yznhy40000gn/T/ipykernel_1842/2233918019.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['propextent_txt'] = data['propextent_txt'].replace('.','unknown')

In [39]:
data.isnull().sum()/data.shape[0] * 100

eventid              0.000000
iyear                0.000000
imonth               0.000000
iday                 0.000000
extended             0.000000
country              0.000000
country_txt          0.000000
region               0.000000
region_txt           0.000000
provstate            9.217877
city                 0.000000
latitude             3.343702
longitude            3.343702
specificity          0.000000
vicinity             0.000000
crit1                0.000000
crit2                0.000000
crit3                0.000000
doubtterr            0.000000
multiple             0.000000
success              0.000000
suicide              0.000000
attacktype1          0.000000
attacktype1_txt      0.000000
targtype1            0.000000
targtype1_txt        0.000000
targsubtype1         0.000000
targsubtype1_txt     0.000000
target1              0.000000
natlty1              0.000000
natlty1_txt          0.000000
gname                0.000000
guncertain1          0.000000
nperps              45.503428
nperpcap            44.291519
claimed             41.988954
weaptype1            0.000000
weaptype1_txt        0.000000
weapsubtype1         0.000000
weapsubtype1_txt     0.000000
nkill                5.688801
nkillus             40.942737
nkillter            42.178136
nwound               9.041392
nwoundus            41.116684
property             0.000000
propextent_txt       0.000000
ishostkid            0.000000
INT_LOG              0.000000
INT_IDEO             0.000000
INT_MISC             0.000000
INT_ANY              0.000000
date                 0.571991
dtype: float64

In [40]:
data = data.drop(range(90455, 90459))

In [41]:
data.to_csv('processed_df.csv',index=False)

In [42]:
data.head()

,eventid,iyear,imonth,iday,extended,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,crit1,crit2,crit3,doubtterr,multiple,success,suicide,attacktype1,attacktype1_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,target1,natlty1,natlty1_txt,gname,guncertain1,nperps,nperpcap,claimed,weaptype1,weaptype1_txt,weapsubtype1,weapsubtype1_txt,nkill,nkillus,nkillter,nwound,nwoundus,property,propextent_txt,ishostkid,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,date
0,197000000001,1970,0,0,0,58,Dominican Republic,2,Central America & Caribbean,NaN,Santo Domingo,18.456792,-69.951164,1.0,0,1,1,1,0.0,0,1.0,0,1,Assassination,14,Private Citizens & Property,68.0,Named Civilian,Julio Guzman,58.0,Dominican Republic,MANO-D,0.0,NaN,NaN,NaN,13,Unknown,0.0,unknown,1.0,NaN,NaN,0.0,NaN,0.0,unknown,0.0,0.0,0.0,0.0,0.0,NaT
1,197000000002,1970,0,0,0,130,Mexico,1,North America,NaN,Mexico city,19.432608,-99.133207,1.0,0,1,1,1,0.0,0,1.0,0,6,Hostage Taking (Kidnapping),7,Government (Diplomatic),45.0,"Diplomatic Personnel (outside of embassy, cons...","Nadine Chaval, daughter",21.0,Belgium,23rd of September Communist League,0.0,7.0,NaN,NaN,13,Unknown,0.0,unknown,0.0,NaN,NaN,0.0,NaN,0.0,unknown,1.0,0.0,1.0,1.0,1.0,NaT
2,197001000001,1970,1,0,0,160,Philippines,5,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,4.0,0,1,1,1,0.0,0,1.0,0,1,Assassination,10,Journalists & Media,54.0,Radio Journalist/Staff/Facility,Employee,217.0,United States,Unknown,0.0,NaN,NaN,NaN,13,Unknown,0.0,unknown,1.0,NaN,NaN,0.0,NaN,0.0,unknown,0.0,-9.0,-9.0,1.0,1.0,NaT
3,197001000002,1970,1,0,0,78,Greece,8,Western Europe,Attica,Athens,37.983773,23.728157,1.0,0,1,1,1,0.0,0,1.0,0,3,Bombing/Explosion,7,Government (Diplomatic),46.0,Embassy/Consulate,U.S. Embassy,217.0,United States,Unknown,0.0,NaN,NaN,NaN,6,Explosives/Bombs/Dynamite,16.0,Unknown Explosive Type,NaN,NaN,NaN,NaN,NaN,1.0,unknown,0.0,-9.0,-9.0,1.0,1.0,NaT
4,197001000003,1970,1,0,0,101,Japan,4,East Asia,NaN,Fukouka,33.580412,130.396361,1.0,0,1,1,1,-9.0,0,1.0,0,7,Facility/Infrastructure Attack,7,Government (Diplomatic),46.0,Embassy/Consulate,U.S. Consulate,217.0,United States,Unknown,0.0,NaN,NaN,NaN,8,Incendiary,0.0,unknown,NaN,NaN,NaN,NaN,NaN,1.0,unknown,0.0,-9.0,-9.0,1.0,1.0,NaT